services:
  postgres:
    image: postgres:15-alpine
    container_name: quantmatrix-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_HOST_PORT}:5432"
    networks:
      - quantmatrix_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: quantmatrix-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_HOST_PORT}:6379"
    networks:
      - quantmatrix_network
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "--raw", "PING" ]
      interval: 10s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ..
      dockerfile: Dockerfile.backend
    container_name: quantmatrix-backend
    env_file:
      - ./env.dev
    ports:
      - "${BACKEND_HOST_PORT}:8000"
    volumes:
      - ..:/app
      - /app/backend/__pycache__
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:6379/0
      - NEW_RELIC_CONFIG_FILE=/app/newrelic.ini
      - NEW_RELIC_APP_NAME=QuantMatrix Backend
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_LOG=stdout
      - NEW_RELIC_LOG_LEVEL=info
    command: sh -c "cd /app && newrelic-admin run-program python -m uvicorn backend.api.main:app --host 0.0.0.0 --port 8000 --log-level info"
    networks:
      - quantmatrix_network
    restart: unless-stopped

  celery_worker:
    build:
      context: ..
      dockerfile: Dockerfile.backend
    container_name: quantmatrix-celery-worker
    env_file:
      - ./env.dev
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:6379/0
      - IBKR_HOST=${IBKR_HOST}
      - NEW_RELIC_CONFIG_FILE=/app/newrelic.ini
      - NEW_RELIC_APP_NAME=QuantMatrix Celery Worker
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_LOG=stdout
      - NEW_RELIC_LOG_LEVEL=info
    volumes:
      - ../backend:/app/backend
      - ../requirements.txt:/app/requirements.txt
      - ../newrelic.ini:/app/newrelic.ini
    depends_on:
      - postgres
      - redis
      - backend
    networks:
      - quantmatrix_network
    command: bash -lc "newrelic-admin run-program celery -A backend.tasks.celery_app worker --loglevel=info"

  celery_beat:
    build:
      context: ..
      dockerfile: Dockerfile.backend
    container_name: quantmatrix-celery-beat
    env_file:
      - ./env.dev
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:6379/0
      - IBKR_HOST=${IBKR_HOST}
      - NEW_RELIC_CONFIG_FILE=/app/newrelic.ini
      - NEW_RELIC_APP_NAME=QuantMatrix Celery Beat
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_LOG=stdout
      - NEW_RELIC_LOG_LEVEL=info
    volumes:
      - ../backend:/app/backend
      - ../requirements.txt:/app/requirements.txt
      - celery_beat_data:/app/celerybeat-schedule
      - ../newrelic.ini:/app/newrelic.ini
    depends_on:
      - postgres
      - redis
      - backend
    networks:
      - quantmatrix_network
    command: bash -lc "newrelic-admin run-program celery -A backend.tasks.celery_app beat --loglevel=info"

  flower:
    build:
      context: ..
      dockerfile: Dockerfile.backend
    container_name: quantmatrix-flower
    env_file:
      - ./env.dev
    environment:
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:6379/0
    ports:
      - "${FLOWER_HOST_PORT}:5555"
    depends_on:
      - redis
      - celery_worker
    networks:
      - quantmatrix_network
    command: bash -lc "export FLOWER_UNAUTHENTICATED_API=1; celery -A backend.tasks.celery_app flower --address=0.0.0.0 --port=5555"

  frontend:
    build:
      context: ..
      dockerfile: Dockerfile.frontend
    container_name: quantmatrix-frontend
    env_file:
      - ./env.dev
    environment:
      - VITE_API_URL=http://localhost:${BACKEND_HOST_PORT}
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "${WEB_HOST_PORT}:3000"
    depends_on:
      - backend
    networks:
      - quantmatrix_network
    command: npm run dev

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: quantmatrix-cloudflared
    env_file:
      - ./env.dev
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TUNNEL_TOKEN}
    depends_on:
      - backend
    networks:
      - quantmatrix_network
    restart: unless-stopped
    profiles:
      - tunnel

networks:
  quantmatrix_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  celery_beat_data:
    driver: local
