"""baseline_autogen

Revision ID: 95b8b27bb6d1
Revises: c0b73efcdaeb
Create Date: 2025-11-13 06:59:59.224887
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "95b8b27bb6d1"
down_revision = 'c0b73efcdaeb'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


