"""baseline_autogen

Revision ID: 95b8b27bb6d1
Revises: c0b73efcdaeb
Create Date: 2025-11-13 06:59:59.224887
"""

from alembic import op
import sqlalchemy as sa

# Import full model metadata to generate tables. This provides a real baseline so
# new environments (and test DBs) can actually migrate to a usable schema.
from backend.models import Base

# revision identifiers, used by Alembic.
revision = "95b8b27bb6d1"
down_revision = 'c0b73efcdaeb'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    # In practice we do not support downgrading the baseline in production.
    # Keep no-op to avoid accidental destructive operations.
    pass
    # ### end Alembic commands ###


