"""market snapshot as_of_timestamp

Revision ID: b6e2a756fdad
Revises: bdf3a705ed08
Create Date: 2026-01-09 17:34:34.085541
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "b6e2a756fdad"
down_revision = 'bdf3a705ed08'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE market_snapshot ADD COLUMN IF NOT EXISTS as_of_timestamp TIMESTAMPTZ")
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE market_snapshot DROP COLUMN IF EXISTS as_of_timestamp")
    # ### end Alembic commands ###



