"""market snapshot v2 indicators

Revision ID: bd62443f14ca
Revises: ab12cd34ef56
Create Date: 2026-01-09 07:53:15.894802
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "bd62443f14ca"
down_revision = 'ab12cd34ef56'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    # Use IF NOT EXISTS so migrations are robust in environments that may have partial schema
    # materialized by test helpers (e.g., Base.metadata.create_all) or reruns.
    op.execute("ALTER TABLE market_snapshot ADD COLUMN IF NOT EXISTS sma_5 DOUBLE PRECISION")
    op.execute("ALTER TABLE market_snapshot ADD COLUMN IF NOT EXISTS sma_14 DOUBLE PRECISION")
    op.execute("ALTER TABLE market_snapshot ADD COLUMN IF NOT EXISTS sma_21 DOUBLE PRECISION")
    op.execute("ALTER TABLE market_snapshot ADD COLUMN IF NOT EXISTS sma_150 DOUBLE PRECISION")
    op.execute("ALTER TABLE market_snapshot ADD COLUMN IF NOT EXISTS atr_14 DOUBLE PRECISION")
    op.execute("ALTER TABLE market_snapshot ADD COLUMN IF NOT EXISTS atr_30 DOUBLE PRECISION")
    op.execute("ALTER TABLE market_snapshot ADD COLUMN IF NOT EXISTS atrp_14 DOUBLE PRECISION")
    op.execute("ALTER TABLE market_snapshot ADD COLUMN IF NOT EXISTS atrp_30 DOUBLE PRECISION")
    op.execute("ALTER TABLE market_snapshot ADD COLUMN IF NOT EXISTS range_pos_20d DOUBLE PRECISION")
    op.execute("ALTER TABLE market_snapshot ADD COLUMN IF NOT EXISTS range_pos_50d DOUBLE PRECISION")
    op.execute("ALTER TABLE market_snapshot ADD COLUMN IF NOT EXISTS range_pos_52w DOUBLE PRECISION")
    op.execute("ALTER TABLE market_snapshot ADD COLUMN IF NOT EXISTS atrx_sma_21 DOUBLE PRECISION")
    op.execute("ALTER TABLE market_snapshot ADD COLUMN IF NOT EXISTS atrx_sma_50 DOUBLE PRECISION")
    op.execute("ALTER TABLE market_snapshot ADD COLUMN IF NOT EXISTS atrx_sma_100 DOUBLE PRECISION")
    op.execute("ALTER TABLE market_snapshot ADD COLUMN IF NOT EXISTS atrx_sma_150 DOUBLE PRECISION")
    op.execute("ALTER TABLE market_snapshot ADD COLUMN IF NOT EXISTS rs_mansfield_pct DOUBLE PRECISION")
    op.execute("ALTER TABLE market_snapshot ADD COLUMN IF NOT EXISTS stage_label_5d_ago VARCHAR(10)")
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE market_snapshot DROP COLUMN IF EXISTS stage_label_5d_ago")
    op.execute("ALTER TABLE market_snapshot DROP COLUMN IF EXISTS rs_mansfield_pct")
    op.execute("ALTER TABLE market_snapshot DROP COLUMN IF EXISTS atrx_sma_150")
    op.execute("ALTER TABLE market_snapshot DROP COLUMN IF EXISTS atrx_sma_100")
    op.execute("ALTER TABLE market_snapshot DROP COLUMN IF EXISTS atrx_sma_50")
    op.execute("ALTER TABLE market_snapshot DROP COLUMN IF EXISTS atrx_sma_21")
    op.execute("ALTER TABLE market_snapshot DROP COLUMN IF EXISTS range_pos_52w")
    op.execute("ALTER TABLE market_snapshot DROP COLUMN IF EXISTS range_pos_50d")
    op.execute("ALTER TABLE market_snapshot DROP COLUMN IF EXISTS range_pos_20d")
    op.execute("ALTER TABLE market_snapshot DROP COLUMN IF EXISTS atrp_30")
    op.execute("ALTER TABLE market_snapshot DROP COLUMN IF EXISTS atrp_14")
    op.execute("ALTER TABLE market_snapshot DROP COLUMN IF EXISTS atr_30")
    op.execute("ALTER TABLE market_snapshot DROP COLUMN IF EXISTS atr_14")
    op.execute("ALTER TABLE market_snapshot DROP COLUMN IF EXISTS sma_150")
    op.execute("ALTER TABLE market_snapshot DROP COLUMN IF EXISTS sma_21")
    op.execute("ALTER TABLE market_snapshot DROP COLUMN IF EXISTS sma_14")
    op.execute("ALTER TABLE market_snapshot DROP COLUMN IF EXISTS sma_5")
    # ### end Alembic commands ###



