"""drop legacy sma_20 from market_snapshot

Revision ID: bdf3a705ed08
Revises: bd62443f14ca
Create Date: 2026-01-09 08:15:26.935674
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "bdf3a705ed08"
down_revision = 'bd62443f14ca'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE market_snapshot DROP COLUMN IF EXISTS sma_20")
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE market_snapshot ADD COLUMN IF NOT EXISTS sma_20 DOUBLE PRECISION")
    # ### end Alembic commands ###



